# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "roda", "~> 3.14"

gem "puma", "~> 3.12"

gem "pry", "~> 0.12.2"

gem "rack-cors", "~> 1.0"

gem "pry-byebug", "~> 3.6"

gem "rbnacl", "~> 6.0"

gem "jwt", "~> 2.1"
